version: 1
builder:
  configs:
    - documentation_targets: [GPKit]
    - platform: ios
      scheme: GPKit
    - platform: tvos
      scheme: GPKit
    - platform: watchos
      scheme: GPKit
    - platform: visionos
      scheme: GPKit
